### ISSUE TITLE
Final project links

### ISSUE THREAD

**Issue by chrisortman** [kirkwood-cis-121-17/exercises#1]
Leave a comment with your link

**Comment by Sophie-WH** [comment]
https://github.com/Sophie-WH/Final-Project.git

My final project is the only program in this repository :)

**Comment by jennarunge** [comment]
https://github.com/kirkwood-cis-121-17/menu_jenna/blob/master/menu_jenna/menu_final.py

**Comment by Kyle-Webber** [comment]
https://github.com/Kyle-Webber/Final_Project

**Comment by lydiahecker** [comment]
https://github.com/lydiahecker/final_project

**Comment by Noahster13** [comment]
https://github.com/Noahster13/Noah-Harp-Final-Project

**Comment by BBrusegaard** [comment]
https://github.com/BBrusegaard/exercises/tree/master/Final_Project

**Comment by Sophie-WH** [comment]
Hello!

**Comment by andyhou2000** [comment]
https://github.com/kirkwood-cis-121-17/menu_andy/blob/master/BetterProject.py

**Comment by kayazdan** [comment]
https://github.com/kayazdan/kaya-final-project

**Comment by alecheil** [comment]
https://github.com/alecheil/final_project.git

**Comment by Cithriaa** [comment]
https://github.com/kirkwood-cis-121-17/Menu-Sophie-Musaab.git
