### ISSUE TITLE
Hey Chris

### ISSUE THREAD

**Issue by schwenker59** [kirkwood-cis-121-17/exercises#3]
@chrisortman What is a way that I can do to add on from when you make your first decision?

**Comment by chrisortman** [comment]
You mean after you pick a part like tower, processor, motherboard ? 
If that's the case then the program calls a function for each of those, and you should be able to display another menu there I think

**Comment by schwenker59** [comment]
Okay I will see what I can do

**Comment by chrisortman** [comment]
Also if it helps to have an example to look at, this is the version of the geometry program that I did earlier in the semester

https://github.com/chrisortman/exercises/blob/master/geometry/geometry.py

**Comment by schwenker59** [comment]
Sweet thank you

**Comment by schwenker59** [comment]
How do I make it to where it has the menu when you first start and you can see everything like, multiple catorgories???

**Comment by chrisortman** [comment]
Not sure I understand. Maybe the order of the statements in main?

**Comment by schwenker59** [comment]
Okay you know how in most of everyones menu that the presented they had opitions to choose from how am I able to do that

**Comment by chrisortman** [comment]
In the code of yours we looked at this morning, the main function had two
while loops, one was prompting and the other displayed the menu. The order
dictates what happens first.

So if you want it to print the menu first then that has to happen before
prompting

**Comment by schwenker59** [comment]
so I have to create like 3 more to get the first menu up??? Or so I can have multiple options to choose from

**Comment by chrisortman** [comment]
Maybe, depends on what you mean by “more”

If it were me I’d make a print menu function that prints the menu and call
it first thing in main

**Comment by schwenker59** [comment]
okay so what I'm meaning is that for my program it starts off by saying choose some parts pretty much and then im starting with the tower and I cant figure out how to get options for that so you can choose

**Comment by chrisortman** [comment]
Add lines before the “choose “ lines that print your menu

**Comment by schwenker59** [comment]
Okay
